### PR TITLE
Add initial blog UI

### PR DESCRIPTION
**Pull request by ashutosh1401**
This is initial version of Blog UI . further changes would be done by your suggestions this tends to solve #12

### CODE REVIEW

**Review by yash982000 — CHANGES_REQUESTED** [review]
Hello, the code seems good but can you add some screenshots?
I am unable to try it now on my device.

**Comment by ashutosh1401** [comment]
Screenshot (245)
Screenshot (246)

**Comment by yash982000** [comment]
@ashutosh1401 Have you done this entirely on Windows?

**Comment by ashutosh1401** [comment]
Yes

**Comment by yash982000** [comment]
@ashutosh1401 Can you also show the responsiveness?
 Apart from it, a bit more changes are suggested for the UI. Let me know what you think and what are your ideas for the same

**Comment by ashutosh1401** [comment]
I forgot to check the responsiveness so now i am working on it and you could also suggest further changes.

**Comment by ashutosh1401** [comment]
**TABLET VIEW**
Screenshot (247)
**MOBILE VIEW**
Screenshot (249)

**Comment by ashutosh1401** [comment]
What are further changes required in this Page ?? @yash982000

**Review by yash982000 — COMMENTED** [review]
I am not sure why but you have kept all the images same?

**Comment by ashutosh1401** [comment]
I could change them it wouldn't take much time is their more changes required

**Comment by yash982000** [comment]
> I could change them it wouldn't take much time is their more changes required

Okay. I don't know much now. @milekag01 Milek has been inactive for a long time. I am trying to contact him. But, it's too long to wait for him now so I am merging this for now. Since I am also hospitalized due to being COVID positive, I won't be so active but will keep checking in between once in a day or so. Thank you for your contribution.

**Review by yash982000 — COMMENTED** [review]
Some of the samples of initial blog UI

**Pull request merged**
